services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:3.5.3
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ../:/app
      - .bashrc:/root/.bashrc
      - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - spark-network

  spark-worker:
    container_name: spark-worker
    image: bitnami/spark:3.5.3
    depends_on:
      - spark-master
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - ../:/app
      - .bashrc:/root/.bashrc
      - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - spark-network

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      # - FLASK_ENV=production
    volumes:
      - ../:/app
    user: root
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
